import { Zeyada } from "next/font/google"
import "./globals.css"
import Providers from "./providers"

const zeyada = Zeyada({
  subsets: ["latin"],
  variable: "--font-signature",
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zeyada.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
